version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: sner-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: sner-maven-{{ checksum "pom.xml" }}
      - restore_cache: # restore the saved cache after the first run or if `package.json` has changed
          key: sner-npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: # saves the project dependencies
          paths:
            - node_modules
          key: sner-npm-{{ checksum "package.json" }}
      - run: mvn clean install